### ISSUE TITLE
crashed multiple times today

### ISSUE THREAD

**Issue by dbmuse** [sdottaka/winmerge-v2#80]
I was copying 8 to 40 k chunks of text into the program.  On occassion it would crash mostly when I was deleting the text from one side of the compare.  I will try to find a repeatable crash.  But it did not happen all the time...  This is not from openning a file and comparing.  I paste text directly in the compare windows.

**Comment by sdottaka** [comment]
Thank you for the report.
What version are you using?

**Comment by dbmuse** [comment]
2.15.3 on windows 7

**Comment by sdottaka** [comment]
I am trying to reproduce the crash, but I have not reproduced it for now.

If you find a reproducible procedure please let me know.

**Comment by dbmuse** [comment]
I tried and could not get a crash to occur.  I looked at windows crash reports but I don't think they are useful.  thank you for checking.

**Comment by GreyMerlin** [comment]
I too tried a large variety of scenarios, using both 64- and 32- bit compilations, both Debug and Release.  No failures encountered.  Please do report a failure if it occurs again!

**Comment by StoyanDimitrov** [comment]
Finally, I'm able to repro the crash, that is hounding me for a while.
STR:
1. Open WinMerge
2. Press `Ctrl+N`
3. In the left pane paste or type
```
a
```
4. In the right pane paste or type
```
{a
}
```
5. Click in the left pane and press `Ctrl+A`
6. With cursor still in left pane paste (typing not triggers the crash)
```
{a
}
```

Observations:
1. Sometimes (while reducing the code that triggers the crash) the crashed application opens an alertbox with some exception not catched or something like that.
2. If in steps 4 and 6 replace the curly brackets with pair of parentheses, square or angle brackets the crash still occurs.

**Comment by GreyMerlin** [comment]
I still cannot reproduce this problem; but we are possibly getting closer   

I am using **Win10 Pro**.  I have tried **WinMerge** 2.15.4.0 (both 32-bit and 64-bit) and 2.14.0-jp-152 (32-bit).  I have tried with and without an end-line character following the steps 3, 4 and 6.  Because this failure _seems_ to require "matching brackets", I presume you are using some **Syntax Highlighting** (from the **View** menu); if so, it would be nice to know which one.  Also, are you using any "plugins" (from the **Plugins** menu)?  There are other configuration options that may be different for your usage than with mine.  So a suggestion...

Could you please go to the **Help** menu and select **Configuration**.  This will produce the file `<user>\Documents\WinMerge\WinMerge.txt` which will be around 10k-12k bytes long.  And then please attach that text file to a reply here.

Also... since this seems to be related to **Copy-Paste**, this could be a funny problem with Locale (natural language) differences between the **Copy** source and the **Paste** destination.   If you could also provide the very simple source file from which the tiny Cut is performed (used in step 6), that will likely be very  helpful.  It would be a good idea to package both the `WinMerge.txt` and the `Copy-Source` text files into a single `.zip` file (for the reply attachment) so that any Locale information is not transformed by being a direct attachment.

Thank You !!

**Comment by StoyanDimitrov** [comment]
> I still cannot reproduce

Because of my false assumptions. Here are updated STR:
1. In order to be on the same page remove WinMerge configuration from the registry. Use 
[remove-winmerge-settings.zip](https://github.com/WinMerge/winmerge-v2/files/2422865/remove-winmerge-settings.zip) or just delete the `Thingamahoochie` branch from `HKCU\Software`.
2. Open latest WinMerge (2.15.4.0, Unicode X64 under Win10 Home x64 in my case).
3. Open `Edit` > `Options`.
4. Go to `Editor` and check the `Automatic rescan` option.
5. Press `OK` to close the `Options`.
6. Press `Ctrl-N`.
7. In the left pane paste or type:
```
a
```
8. In the right pane paste or type:
```
{a
}
```
9. Click in the left pane and press `Ctrl+A`
10. With cursor still in left pane paste (typing does not trigger crash):
```
{a
}
```
Following those steps I was able to consistently reproduce under Win7 x64 same WinMerge.
Flipping `Automatic rescan` option back to disabled prevents the crash.

**Comment by GreyMerlin** [comment]
Well... I never got back to studying this problem adequately in depth.  However, I did a brief study (back when the problem was still fresh), and I noticed that the code to handle a **Paste** operation has significantly different checking than the code that handles **Typing**.  The crash you note in `step 10` is related to this difference in the checking.

I too will consider the issue **Closed** ... the general End-Of-Line handling seems reasonably stable now (2.16.0.0).
