### ISSUE TITLE
Line filters in prediff?

### ISSUE THREAD

**Issue by manavortex** [sdottaka/winmerge-v2#83]
Hello there, 

while I found [this|http://regexfilterforw.sourceforge.net/], I haven't been able to get it to work. I'm using Winmerge from command line almost exclusively, and my usecase is that I'd like to ignore certain changes by regex. 
Is there a way to tell WinMerge not to mark a change if it is 
`LINE<A>MORELINE <-> LINE<B>MORELINE? `
If yes, how? If no, could you include it? I would appreciate it a lot.

Is there a way to tell WinMerge not to open if I call it via command line and one of the files doesn't exist?

Thank you for making this.

**Comment by sdottaka** [comment]
WinMerge2011(https://bitbucket.org/jtuc/winmerge2011) can do it.
https://bitbucket.org/jtuc/winmerge2011/issues/148/ignore-specific-words-in-a-comparison

I want that function, but it takes a while to implement it.
So I've just made the following ad-hoc plug-in.

https://raw.githubusercontent.com/sdottaka/winmerge-v2/402f452c2a16ee4a26732086ad0ea559d9f2f0c4/Plugins/dlls/PrediffLineFilter.sct

### How To Use

1.  Copy PrediffLineFilter.sct to C:\Program Files\WinMerge\MergePlugins
2.  Setup the plugin as follows:
<img width="940" alt="predifflinefilter" src="https://user-images.githubusercontent.com/98126/38469738-936bca7c-3b94-11e8-8785-0e395834cc9c.png">
3. Apply the plugin as follows:
<img width="960" alt="predifflinefilter2" src="https://user-images.githubusercontent.com/98126/38469741-9c56d622-3b94-11e8-888f-225fe37a45c6.png">

**Comment by manavortex** [comment]
Awesome, thanks!

**Comment by KalCoder** [comment]
This does not work in the latest version of WinMerge I have a huge 30K line plus document that I am comparing, but I renamed a variable from "Data" to "SSRRData" and it works with the above test case A to B or <A> to <B> but i have tried everything and I just had to make a copy of my code where I reverted the varible rename to Data and was able to use winMerge to find my bug.

Maybe do some testing and see why when the two terms being compared are not the same length it does not work or something. I appreciate you.

**Comment by sdottaka** [comment]
@KalCoder 

I tried the following, but I couldn't reproduce the problem of PrediffLineFilter not working.

Could you please attach a screenshot of the file you compared and the PrediffLineFilter settings window so that we can reproduce the problem?

(Note that the latest version seems to have a problem with the Plugins→Prediffer menu not displaying correctly, which will be fixed later. Please use the Apply Prediffer menu item instead.)

![Image](https://github.com/user-attachments/assets/8ea8f0b7-d731-4c9c-927e-36baf17e899f)

![Image](https://github.com/user-attachments/assets/d6282752-93b3-40e2-90a6-8248300efa04)
